name: 'Setup Node.js'
description: 'Set up Node.js with caching and install dependencies'
inputs:
  install-deps:
    description: 'Whether to install dependencies'
    required: false
    default: 'true'
  node-version:
    description: 'Node.js version'
    required: false
    default: '20'

runs:
  using: 'composite'
  steps:
  - name: Setup Node.js
    uses: actions/setup-node@v4
    with:
      node-version: ${{ inputs.node-version }}
      cache: 'npm'
      registry-url: 'https://registry.npmjs.org'

  - name: Install dependencies
    if: inputs.install-deps == 'true'
    run: npm ci
    shell: bash
