name: 'Setup Docker Build'
description: 'Set up Docker Buildx with QEMU for multi-platform builds'
inputs:
  platforms:
    description: 'Target platforms for Docker build'
    required: false
    default: 'linux/amd64,linux/arm64'

runs:
  using: 'composite'
  steps:
  - name: Set up QEMU
    uses: docker/setup-qemu-action@v3

  - name: Set up Docker Buildx
    uses: docker/setup-buildx-action@v3
